# Generated by Django 5.2.11 on 2026-03-01 23:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Disponibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_apertura", models.TimeField()),
                ("hora_cierre", models.TimeField()),
                (
                    "horas_bloqueadas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de horas bloqueadas en formato [9, 10, 14] representando las 9:00, 10:00, 14:00",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Disponibilidades",
                "ordering": ["dia_semana", "hora_apertura"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cita", "Cita"),
                            ("bloqueo", "Bloqueo Administrativo"),
                        ],
                        default="cita",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reservas",
                "ordering": ["fecha", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duracion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Duración del servicio en horas",
                        max_digits=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="aurora_studio_app.usuario",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de teléfono inválido",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clientes",
            },
            bases=("aurora_studio_app.usuario",),
        ),
        migrations.CreateModel(
            name="DetalleCita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_aplicado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del servicio en el momento de la reserva",
                        max_digits=10,
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="aurora_studio_app.reserva",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="aurora_studio_app.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Detalles de Citas",
            },
        ),
        migrations.AddField(
            model_name="reserva",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente que hace la reserva (null para bloqueos administrativos)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="aurora_studio_app.cliente",
            ),
        ),
    ]
