# Generated by Django 5.2.11 on 2026-02-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_studio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
