# Generated by Django 5.2.11 on 2026-02-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_studio_app', '0002_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado')], default='pendiente', max_length=20),
        ),
    ]
