# Generated by Django 5.2.11 on 2026-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_studio_app', '0003_reserva_codigo_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to='espacios/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], editable=False, max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contenidos visuales',
                'ordering': ['-creado_en'],
            },
        ),
    ]
