"""
Django settings for aurora_studio project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote_plus

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-_u#_z*8*5d*cc5w2vs4lr(5-d5tksjjdn4%9^+myl)22+@-o1m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'aurora_studio_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aurora_studio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'frontend' / 'templates',  # Templates del frontend separado
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aurora_studio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('USE_POSTGRES', '0') == '1':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'aurora_db'),
            'USER': os.environ.get('POSTGRES_USER', 'aurora_user'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'aurora_password'),
            'HOST': os.environ.get('POSTGRES_HOST', 'db'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.environ.get('DJANGO_LANGUAGE_CODE', 'es')

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Evitar advertencias si el directorio no existe en desarrollo
STATICFILES_DIRS = [p for p in (BASE_DIR / 'frontend' / 'static', BASE_DIR / 'static') if p.exists()]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Para producción (collectstatic)

# Internacionalización
from django.utils.translation import gettext_lazy as _  # noqa: E402

LANGUAGES = [
    ('es', _('Español')),
    ('en', _('English')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========== CONFIGURACIÓN DE AURORA STUDIO ==========

# Ubicación del local
BUSINESS_NAME = os.environ.get('BUSINESS_NAME', 'Aurora Studio')
BUSINESS_ADDRESS = os.environ.get(
    'BUSINESS_ADDRESS',
    'Cll 63 Sur #43 a12 local Torre Alcántara',
)
BUSINESS_MAPS_EMBED_URL = os.environ.get(
    'BUSINESS_MAPS_EMBED_URL',
    f'https://www.google.com/maps?q={quote_plus(BUSINESS_ADDRESS)}&output=embed',
)
BUSINESS_MAPS_DIRECTIONS_URL = os.environ.get(
    'BUSINESS_MAPS_DIRECTIONS_URL',
    f'https://www.google.com/maps/search/?api=1&query={quote_plus(BUSINESS_ADDRESS)}',
)

# Sistema de notificaciones
# Opciones visibles: 'mock' (imprime en consola) o 'smtp' (envía por el microservicio Flask)
NOTIFICATION_SENDER = os.environ.get('NOTIFICATION_SENDER', 'mock').lower()
NOTIFICATIONS_SERVICE_URL = os.environ.get(
    'NOTIFICATIONS_SERVICE_URL',
    'http://localhost:5001/api/v2/funcionalidad',
)

# Celery / Redis
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)

# Habilitar envío de notificaciones de forma asíncrona mediante Celery
NOTIFICATIONS_ASYNC = os.environ.get('NOTIFICATIONS_ASYNC', '0') == '1'

# Configuración de la API externa de motos (proveída por otro equipo)
EXTERNAL_MOTOS_BASE_URL = os.environ.get(
    'EXTERNAL_MOTOS_BASE_URL',
    'http://52.54.140.72/api/public/v1/motos/'
)
EXTERNAL_MOTOS_API_KEY = os.environ.get('EXTERNAL_MOTOS_API_KEY', 'yamaha-grupo-2026')
